package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005CBB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3F)
val md_theme_light_secondary = Color(0xFF555F71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E3F8)
val md_theme_light_onSecondaryContainer = Color(0xFF121C2B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)

val md_theme_dark_primary = Color(0xFFABC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F66)
val md_theme_dark_primaryContainer = Color(0xFF004590)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E3FF)
val md_theme_dark_secondary = Color(0xFFBDC7DC)
val md_theme_dark_onSecondary = Color(0xFF273141)
val md_theme_dark_secondaryContainer = Color(0xFF3E4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E3F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
